<template>
    <div class="">
        <div class="contain overflow-y-auto bg-[#0C0A08]">
            <!-- header -->
            <div class="item group">
                <p @click="goHome" class="group-hover:scale-105 transition-all cursor-pointer">hiragana</p>
            </div>
            <!-- section -->

            
            <div class="w-full h-full flex items-center justify-center flex-col flex-wrap gap-10 pb-16">
                <!-- hiragana table -->
                <HiraganaTable :checkSelected="checkSelected" :selectLetter="selectLetter" :selectAll="selectAll" :selectClear="selectClear" :isOpen="isOpen" ></HiraganaTable>

                <!-- shuffleresult -->
                <div v-if="!selected.length<=0" class="w-64 h-80  border md:mx-0 mx-auto flex items-center flex-col py-8 bg-[#390097]">
                    <div id="resultContainer" class="border w-40 h-24  flex items-center justify-center neou bg-[#390097] ">
                        <p class="text-4xl text-white font-bold ">{{ result }}</p>
                    </div>
                    <button id="shuffleBtn" @click="shuffleLetter" class="bg-[#390097] border-[#00F171] hover:border-[#390097] hover:bg-[#00F171] border text-white font-semibold px-3 py-1.5 rounded-lg mt-auto neou-btn " >Shuffle</button>
                </div>

        </div>
        </div>
    </div>
</template>

<script setup>
import router from '/src/router';
import {computed, ref } from 'vue';

import HiraganaTable from '/src/components/HiraganaTable.vue';
const selected = ref([])
const result = ref("")
const isOpen = ref(true)
const goHome=()=>{
    router.push("/")
}

const selectLetter=name=>{
    if(checkSelected(name)){
        selected.value =  selected.value.filter(i => i != name)
    }
    else{
        selected.value.push(name)
    }
}

const checkSelected =(name)=>{
return selected.value.includes(name)
}

const shuffleLetter = ()=>{
    isOpen.value=false
    const container = document.querySelector("#resultContainer")
    const shuffleBtn = document.querySelector("#shuffleBtn")
    container.classList.add("flip-horizontal-bottom")
    shuffleBtn.classList.add("!pointer-events-none")
    setTimeout(() => {
        container.classList.remove("flip-horizontal-bottom")
        shuffleBtn.classList.remove("!pointer-events-none")
    }, 500);
    const length = selected.value.length -1
    const index = Math.floor(Math.random() * length)
    console.log('length :>> ', length);
    console.log('index :>> ', index);
    result.value = selected.value[index]

}

const selectAll=()=>{
    selected.value=["a", "ka", "sa", "shi", "ki", "i", "u", "ku", "su", "se", "ke", "e", "o", "ko", "so", "ta", "tsu", "chi", "te", "to", "no", "ne", "nu", "ni", "na", "ha", "hi", "he", "fu", "ho", "me", "mu", "mi", "ma", "ya", "yu", "yo", "mo", "ro", "re", "ru", "ra", "wa", "ri", "wi", "we", "wo"]
}
const selectClear=()=>{
    selected.value=[]
}
</script>


<style  scoped>
.flip-horizontal-bottom {
	-webkit-animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-8-25 13:43:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-horizontal-bottom
 * ----------------------------------------
 */
 @-webkit-keyframes flip-horizontal-bottom {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-360deg);
            transform: rotateX(-360deg);
  }
}
@keyframes flip-horizontal-bottom {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-360deg);
            transform: rotateX(-360deg);
  }
}


.neou{
box-shadow:  -10px 10px 1px #00cf61,
             10px -10px 1px #0fff7f;
}

.neou-btn{
box-shadow:  -5px 5px 1px #00F171,
             5px -5px 1px #00F171;
}
.neou-btn:hover{
box-shadow:  -5px 5px 1px #390097,
             5px -5px 1px #390097;
}

.contain{
    @apply
    container mx-auto 
    min-h-[100dvh] md:min-h-screen 
    flex items-center justify-start flex-col gap-4
}

.item{
    @apply
    w-full h-24 
    text-center
    text-white
    select-none transition-all
    font-japan-wave
    flex items-center justify-center flex-col
    text-4xl group-hover:font-bold
    uppercase
    before:content-[''] before:w-4 before:h-4 before:rounded-full before:bg-[#be0029]
    hover:before:scale-110 before:transition-all
}


</style>